host: 0.0.0.0

sass:
    style: compressed

plugins:
  - jekyll-minifier
  - jekyll-autoprefixer
  
jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true

autoprefixer:
  only_production: true

timezone: Europe/Amsterdam

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "NS Design 3.0"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title